"""Index itinerary_id

Revision ID: 8991f8af1ab0
Revises: 1202299575f8
Create Date: 2025-07-22 11:35:13.610844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8991f8af1ab0'
down_revision: Union[str, None] = '1202299575f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_itinerary_itinerary_id', 'itinerary', ['itinerary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_itinerary_itinerary_id', table_name='itinerary')
    # ### end Alembic commands ###
