"""Add return dates to Itinerary

Revision ID: 8d2ec14f9542
Revises: e79796ce4aa5
Create Date: 2024-11-26 15:38:33.331354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '8d2ec14f9542'
down_revision: Union[str, None] = 'e79796ce4aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary', sa.Column('rlocal_departure', sa.DateTime(), nullable=True))
    op.add_column('itinerary', sa.Column('rlocal_arrival', sa.DateTime(), nullable=True))
    con = op.get_bind()
    con.execute(text("""
UPDATE itinerary 
SET
    rlocal_departure=(SELECT MIN(local_departure) FROM itinerary2route,route WHERE _return=1 AND itinerary2route.route_id=route.id AND itinerary.search_id=itinerary2route.search_id AND itinerary.id=itinerary2route.itinerary_id),
    rlocal_arrival=(SELECT MAX(local_arrival) FROM itinerary2route,route WHERE _return=1 AND itinerary2route.route_id=route.id AND itinerary.search_id=itinerary2route.search_id AND itinerary.id=itinerary2route.itinerary_id)
WHERE rlocal_departure IS NULL"""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itinerary', 'rlocal_arrival')
    op.drop_column('itinerary', 'rlocal_departure')
    # ### end Alembic commands ###
