"""Index price

Revision ID: 8f8e7793bd21
Revises: c86ad1adf385
Create Date: 2024-09-24 11:50:17.138277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8e7793bd21'
down_revision: Union[str, None] = 'c86ad1adf385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_itinerary_price'), 'itinerary', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_price'), table_name='itinerary')
    # ### end Alembic commands ###
