"""Add actual column to Search table

Revision ID: 95501739f5dc
Revises: 26ea3feffe8a
Create Date: 2024-10-09 11:20:59.054920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95501739f5dc'
down_revision: Union[str, None] = '26ea3feffe8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('route_idx', 'itinerary2route', ['route_id'], unique=False)
    op.add_column('search', sa.Column('actual', sa.BOOLEAN(), nullable=False,server_default="0"))
    op.create_index(op.f('ix_search_actual'), 'search', ['actual'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_actual'), table_name='search')
    op.drop_column('search', 'actual')
    op.drop_index('route_idx', table_name='itinerary2route')
    # ### end Alembic commands ###
