"""Create tables

Revision ID: e79796ce4aa5
Revises: 6d894fcd61ff
Create Date: 2024-11-11 16:36:08.152199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79796ce4aa5'
down_revision: Union[str, None] = '6d894fcd61ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('combination_id', sa.String(length=24), nullable=False),
    sa.Column('flyFrom', sa.String(length=3), nullable=False),
    sa.Column('flyTo', sa.String(length=3), nullable=False),
    sa.Column('cityFrom', sa.String(length=50), nullable=False),
    sa.Column('cityCodeFrom', sa.String(length=3), nullable=False),
    sa.Column('cityTo', sa.String(length=50), nullable=False),
    sa.Column('cityCodeTo', sa.String(length=3), nullable=False),
    sa.Column('local_departure', sa.DateTime(), nullable=False),
    sa.Column('local_arrival', sa.DateTime(), nullable=False),
    sa.Column('airline', sa.String(length=2), nullable=False),
    sa.Column('flight_no', sa.Integer(), nullable=False),
    sa.Column('operating_carrier', sa.String(length=2), nullable=False),
    sa.Column('operating_flight_no', sa.String(length=4), nullable=False),
    sa.Column('fare_basis', sa.String(length=10), nullable=False),
    sa.Column('fare_category', sa.String(length=1), nullable=False),
    sa.Column('fare_classes', sa.String(length=1), nullable=False),
    sa.Column('_return', sa.Integer(), nullable=False),
    sa.Column('bags_recheck_required', sa.Boolean(), nullable=False),
    sa.Column('vi_connection', sa.Boolean(), nullable=False),
    sa.Column('guarantee', sa.Boolean(), nullable=False),
    sa.Column('equipment', sa.String(length=4), nullable=True),
    sa.Column('vehicle_type', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search',
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('range_start', sa.Date(), nullable=False),
    sa.Column('range_end', sa.Date(), nullable=False),
    sa.Column('results', sa.Integer(), nullable=False),
    sa.Column('actual', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('search_id')
    )
    op.create_index(op.f('ix_search_actual'), 'search', ['actual'], unique=False)
    op.create_table('itinerary',
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('flyFrom', sa.String(length=3), nullable=False),
    sa.Column('flyTo', sa.String(length=3), nullable=False),
    sa.Column('cityFrom', sa.String(length=50), nullable=False),
    sa.Column('cityCodeFrom', sa.String(length=3), nullable=False),
    sa.Column('cityTo', sa.String(length=50), nullable=False),
    sa.Column('cityCodeTo', sa.String(length=3), nullable=False),
    sa.Column('countryFromCode', sa.String(length=2), nullable=False),
    sa.Column('countryFromName', sa.String(length=50), nullable=False),
    sa.Column('countryToCode', sa.String(length=2), nullable=False),
    sa.Column('countryToName', sa.String(length=50), nullable=False),
    sa.Column('local_departure', sa.DateTime(), nullable=False),
    sa.Column('local_arrival', sa.DateTime(), nullable=False),
    sa.Column('nightsInDest', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('durationDeparture', sa.Integer(), nullable=False),
    sa.Column('durationReturn', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('conversionEUR', sa.Float(), nullable=False),
    sa.Column('availabilitySeats', sa.Integer(), nullable=True),
    sa.Column('airlines', sa.String(length=30), nullable=False),
    sa.Column('booking_token', sa.String(length=2048), nullable=False),
    sa.Column('deep_link', sa.String(length=2048), nullable=False),
    sa.Column('facilitated_booking_available', sa.Boolean(), nullable=False),
    sa.Column('pnr_count', sa.Integer(), nullable=False),
    sa.Column('has_airport_change', sa.Boolean(), nullable=False),
    sa.Column('technical_stops', sa.Integer(), nullable=False),
    sa.Column('throw_away_ticketing', sa.Boolean(), nullable=False),
    sa.Column('hidden_city_ticketing', sa.Boolean(), nullable=False),
    sa.Column('virtual_interlining', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search.search_id'], ),
    sa.PrimaryKeyConstraint('search_id', 'id')
    )
    op.create_index(op.f('ix_itinerary_price'), 'itinerary', ['price'], unique=False)
    op.create_table('itinerary2route',
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('itinerary_id', sa.String(length=255), nullable=False),
    sa.Column('route_id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['search_id', 'itinerary_id'], ['itinerary.search_id', 'itinerary.id'], ),
    sa.PrimaryKeyConstraint('search_id', 'itinerary_id', 'route_id')
    )
    op.create_index('route_idx', 'itinerary2route', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('route_idx', table_name='itinerary2route')
    op.drop_table('itinerary2route')
    op.drop_index(op.f('ix_itinerary_price'), table_name='itinerary')
    op.drop_table('itinerary')
    op.drop_index(op.f('ix_search_actual'), table_name='search')
    op.drop_table('search')
    op.drop_table('route')
    # ### end Alembic commands ###
